import type { Metadata } from "next";
import { Geist, Geist_Mono, Source_Serif_4 } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sourceSerif = Source_Serif_4({
  variable: "--font-source-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${sourceSerif.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <script
          // Runs before paint to avoid a flash of the wrong theme/font.
          // Keys must match STORAGE_KEY in lib/theme.ts and lib/font.ts.
          dangerouslySetInnerHTML={{
            __html: `try {
              var t = localStorage.getItem("theme-preference");
              if (t === "light" || t === "dark") {
                document.documentElement.setAttribute("data-theme", t);
              }
              var f = localStorage.getItem("font-preference");
              if (f === "serif" || f === "system") {
                document.documentElement.setAttribute("data-font", f);
              }
            } catch (e) {}`,
          }}
        />
        {children}
      </body>
    </html>
  );
}
